const db = require('./db');

const itemsByCategory = {
  'Ice Creams & Desserts': [
    { name: '1l Butter Scotch 1 Ltr', price: 130 },
    { name: '1l Pista 1 Ltr', price: 100 },
    { name: '1l Vanilla 1 Ltr', price: 100 },
    { name: 'ANJEER BADAM', price: 120 },
    { name: 'Anjeer Badam 1', price: 120 },
    { name: 'Anjeer Badam 2', price: 240 },
    { name: 'Anjeer Badam Bulk', price: 500 },
    { name: 'Anjeer Badam Single -150', price: 150 },
    { name: 'Anjeer Badam Single-300', price: 300 },
    { name: 'Anjeer Badam Spl Single -300', price: 300 },
    { name: 'ANJEER BADAM(SPECIAL )', price: 200 },
    { name: 'B D C 500ml', price: 150 },
    { name: 'B D C Single-300', price: 300 },
    { name: 'B.D.C', price: 100 },
    { name: 'B.d.c Bulk', price: 400 },
    { name: 'B.D.C(SPECIAL )', price: 150 },
    { name: 'Bdc 1', price: 100 },
    { name: 'Bdc 150', price: 150 },
    { name: 'Bdc 2', price: 200 },
    { name: 'Bdc Bulk', price: 400 },
    { name: 'Black Currant', price: 100 },
    { name: 'Black Currant 3', price: 300 },
    { name: 'Black Currant S.p.l', price: 150 },
    { name: 'Black Current', price: 100 },
    { name: 'Black Forest', price: 120 },
    { name: 'Black Forest 1', price: 120 },
    { name: 'Black Forest 2', price: 240 },
    { name: 'Black Forest 77', price: 77 },
    { name: 'Black Forest Bulk', price: 450 },
    { name: 'Black Forest Single-125', price: 125 },
    { name: 'Black Forest Single-300', price: 300 },
    { name: 'BLACK FOREST(SPECIAL )', price: 180 },
    { name: 'Black Forest.', price: 120 },
    { name: 'BUTTER CARMEL DELIGHT', price: 150 },
    { name: 'BUTTER CHOFUDGE', price: 150 },
    { name: 'BUTTER SCOTCH', price: 100 },
    { name: 'Butter Scotch Bulk', price: 400 },
    { name: 'BUTTER SCOTCH(SPECIAL )', price: 150 },
    { name: 'Butterscotch 95', price: 95 },
    { name: 'Butterscotch Pre', price: 120 },
    { name: 'Butterscotch Premium 2', price: 240 },
    { name: 'Butterscotch Premium 1', price: 120 },
    { name: 'Butterscotch Single-100', price: 100 },
    { name: 'Caramel Bulk', price: 400 },
    { name: 'Caramel Pre 3', price: 360 },
    { name: 'Caramel Special', price: 150 },
    { name: 'Casata', price: 60 },
    { name: 'Choco Bar', price: 30 },
    { name: 'Chocobar', price: 30 },
    { name: 'CHOCOLATE', price: 100 },
    { name: 'Chocolate 1', price: 100 },
    { name: 'Chocolate 2', price: 200 },
    { name: 'Chocolate Bulk', price: 400 },
    { name: 'CHOCOLATE HERO', price: 150 },
    { name: 'Chocolate Single-125', price: 125 },
    { name: 'Chocolate Single-250', price: 250 },
    { name: 'CHOCOLATE(SPECIAL )', price: 150 },
    { name: 'Cup Vennala', price: 30 },
    { name: 'D.f.l Special Bulk', price: 500 },
    { name: 'DARK CHOCOLATE FUDGE', price: 150 },
    { name: 'Dft Spl 900', price: 900 },
    { name: 'Feast', price: 40 },
    { name: 'Feast 30', price: 30 },
    { name: 'Green Pista', price: 100 },
    { name: 'GREEN PISTA(SPECIAL )', price: 150 },
    { name: 'Kasata', price: 60 },
    { name: 'KHEER', price: 100 },
    { name: 'Kheer 1', price: 100 },
    { name: 'Kheer 2', price: 200 },
    { name: 'Kheer 90', price: 90 },
    { name: 'Kheer Bulk', price: 400 },
    { name: 'Kheer Single-150', price: 150 },
    { name: 'Kheer Single-300', price: 300 },
    { name: 'KHEER(SPECIAL )', price: 150 },
    { name: 'Kulfi Stick', price: 40 },
    { name: 'Lolly Grap', price: 20 },
    { name: 'Lolly Mango', price: 20 },
    { name: 'Lolly Stawbeery', price: 20 },
    { name: 'MALAI KHAJA', price: 120 },
    { name: 'Malai Khaja 500ml', price: 180 },
    { name: 'Malai Khaja Bulk', price: 500 },
    { name: 'Malai Khaja Bulk9', price: 900 },
    { name: 'Malai Khaja Single-300', price: 300 },
    { name: 'MALAI KHAJA(SPECIAL )', price: 180 },
    { name: 'Malai Kulfi 35', price: 35 },
    { name: 'Malaikhaja Pre', price: 150 },
    { name: 'Malaikhaja Single-150', price: 150 },
    { name: 'Mango', price: 100 },
    { name: 'Mango 1', price: 100 },
    { name: 'Mango 100', price: 100 },
    { name: 'Mango 1000ml', price: 200 },
    { name: 'Mango 2', price: 200 },
    { name: 'Mango 500ml', price: 120 },
    { name: 'Mango Ball', price: 50 },
    { name: 'Maska Millon 1', price: 120 },
    { name: 'Maska Millon 2', price: 240 },
    { name: 'Maska Millon Single-250', price: 250 },
    { name: 'Maskmilon Single-125', price: 125 },
    { name: 'Matka Kulfi', price: 60 },
    { name: 'Matra Kulti', price: 60 },
    { name: 'Musk Millon Bulk', price: 400 },
    { name: 'MUSKMILLON', price: 120 },
    { name: 'MUSKMILLON(SPECIAL )', price: 160 },
    { name: 'NULTY CHOCOLATE', price: 120 },
    { name: 'NUT O NUT', price: 140 },
    { name: 'Nutty Bar', price: 50 },
    { name: 'Nutty Chocolate', price: 120 },
    { name: 'OREO FLUGE', price: 130 },
    { name: 'Panjabi Kulifi', price: 50 },
    { name: 'Pina Chikk 125', price: 125 },
    { name: 'PINAPPLE CHIKK', price: 120 },
    { name: 'PINAPPLE CHIKK(SPECIAL )', price: 160 },
    { name: 'Pine Chhiki 1', price: 120 },
    { name: 'Pine Chhiki 2', price: 240 },
    { name: 'Pine Chikki Bulk', price: 400 },
    { name: 'Pine Chikki Single-250', price: 250 },
    { name: 'Pinechikki Single-125', price: 125 },
    { name: 'Pink Gouva', price: 100 },
    { name: 'Pinkgouva', price: 100 },
    { name: 'Pinkgouva 1', price: 100 },
    { name: 'Pinkgouva 250', price: 250 },
    { name: 'Pista', price: 100 },
    { name: 'Pista 1000 Ml', price: 200 },
    { name: 'Pista Bulk', price: 400 },
    { name: 'Pista Pre 150', price: 150 },
    { name: 'Pista Single-80', price: 80 },
    { name: 'RAJ BHOGH', price: 120 },
    { name: 'Raj Bhogh 1', price: 120 },
    { name: 'Raj Bhogh 2', price: 240 },
    { name: 'Raj Bhogh Bulk', price: 450 },
    { name: 'Raj Bhogh Single-150', price: 150 },
    { name: 'Raj Bhogh Single-300', price: 300 },
    { name: 'RAJ BHOGH(SPECIAL )', price: 180 },
    { name: 'Rajbhogu 9', price: 90 },
    { name: 'Red Velvet', price: 130 },
    { name: 'Red Velvet 1', price: 130 },
    { name: 'Red Velvet 2', price: 260 },
    { name: 'Red Velvet Bulk', price: 500 },
    { name: 'Red Velvet Single-250', price: 250 },
    { name: 'RED VELVET(SPECIAL )', price: 180 },
    { name: 'Redvelvet Single-125', price: 125 },
    { name: 'Rose', price: 80 },
    { name: 'Sitapal', price: 120 },
    { name: 'Sitapal 500ml', price: 180 },
    { name: 'Sitapal 500ml Single 125', price: 125 },
    { name: 'Sitapal(special )', price: 160 },
    { name: 'Sitaphal 1000ml', price: 300 },
    { name: 'Sitaphal Bulk', price: 500 },
    { name: 'Small Cone Butter Scorch', price: 40 },
    { name: 'Small Cone Chocolate', price: 40 },
    { name: 'SPICES GOUVA', price: 110 },
    { name: 'SPICES GOUVA(SPECIAL )', price: 150 },
    { name: 'Spicy Gouva 1', price: 110 },
    { name: 'Spicy Gouva 2', price: 220 },
    { name: 'Spicy Gouva Single-125', price: 125 },
    { name: 'Spicy Gouva Single-300', price: 300 },
    { name: 'Spl Caramel 1', price: 140 },
    { name: 'Spl Caramel 2', price: 280 },
    { name: 'Spl Caramel Single-300', price: 300 },
    { name: 'Spl Dft 150', price: 150 },
    { name: 'Spl Dft Single 300', price: 300 },
    { name: 'Spycy Gouva Bulk', price: 450 },
    { name: 'Straberry', price: 90 },
    { name: 'Strawberry', price: 90 },
    { name: 'Strawberry 1', price: 90 },
    { name: 'Strawberry 1l 100/-', price: 100 },
    { name: 'Strawberry 2', price: 180 },
    { name: 'Strawberry Balls', price: 50 },
    { name: 'Strawberry Bulk', price: 350 },
    { name: 'Strawberry Single-150', price: 150 },
    { name: 'Strawberry Single-75', price: 75 },
    { name: 'STREW Berry', price: 90 },
    { name: 'STREWBERY(SPECIAL )', price: 130 },
    { name: 'Sunday', price: 100 },
    { name: 'Super Sunday', price: 150 },
    { name: 'Top Cone Butterscotch', price: 50 },
    { name: 'Top Cone Chocolate', price: 50 },
    { name: 'VANILLA', price: 80 },
    { name: 'Vanilla Single 500ml', price: 120 },
    { name: 'VANILLA(SPECIAL )', price: 120 },
    { name: 'Vannela Bulk', price: 300 },
    { name: 'Vannila Pre 3', price: 240 },
    { name: 'Vannila Premium 1', price: 120 },
    { name: 'Vannila Premium 2', price: 240 },
    { name: 'Vannila Single 1000 Ml 150', price: 150 },
    { name: 'Vennala Ball', price: 40 },
    { name: 'YOURS CHOCO FUDGE', price: 150 }
  ],
  'Milkshakes & Mocktails': [
    { name: 'BANNA STREWBERRY MILK SHAKE', price: 120 },
    { name: 'Blackforest Milk Shake', price: 140 },
    { name: 'BLUE LOGOOON', price: 100 },
    { name: 'BOOMY BLUE', price: 100 },
    { name: 'Caramel Milk Shake', price: 120 },
    { name: 'CHOCOLUTE MILK SHAKE', price: 130 },
    { name: 'CREAMY VANNILA MILK SHAKE', price: 110 },
    { name: 'DRY FRUIT LOVE', price: 150 },
    { name: 'DRY FRUIT MASTI', price: 160 },
    { name: 'DRY FRUIT MILK SHAKE', price: 150 },
    { name: 'DRY FRUIT TEMPLTAL', price: 150 },
    { name: 'DRY FRUIT TEMPLTAL(SPECIAL )', price: 180 },
    { name: 'FRUIT OF FEREST', price: 130 },
    { name: 'FRUIT OF FUN', price: 120 },
    { name: 'FRUIT OF JOY', price: 120 },
    { name: 'HONES MOON DELIGHT', price: 140 },
    { name: 'HONES MOON DELIGHT(SPECIAL )', price: 180 },
    { name: 'KAJU BUTTER SCOTCH MILK SHAKE', price: 150 },
    { name: 'LIME MINT PRO', price: 90 },
    { name: 'MANGO BADAM MILK SHAKE', price: 140 },
    { name: 'Mask Millon Milkshake', price: 120 },
    { name: 'MINT LIME', price: 80 },
    { name: 'MOCKTAILS', price: 100 },
    { name: 'OREO MILK SHAKE', price: 130 },
    { name: 'PISTA MILK SHAKE', price: 120 },
    { name: 'Special Fruit Punch', price: 150 },
    { name: 'STREWBERRY MILK SHAKE', price: 110 }
  ],
  'Fresh Juices': [
    { name: 'APPLE JUICE', price: 80 },
    { name: 'CARROT JUICE', price: 70 },
    { name: 'GRAPE JUICE', price: 70 },
    { name: 'GREEN APPLE', price: 90 },
    { name: 'MUSAMBI JUICE', price: 60 },
    { name: 'PINAPPLE JUICE', price: 80 },
    { name: 'POMOGRANATE JUICE', price: 90 }
  ],
  'Fast Food & Snacks': [
    { name: 'Chees Corn Nuggets', price: 110 },
    { name: 'CHEES CORN NUGGTS', price: 110 },
    { name: 'Chi Chees Pizza', price: 200 },
    { name: 'Chi Chees Sandwich', price: 140 },
    { name: 'CHI CORN WRAPS', price: 150 },
    { name: 'CHI LEG 1PC', price: 60 },
    { name: 'CHI LEG 2 PCS', price: 110 },
    { name: 'Chi Leg 2pcs', price: 110 },
    { name: 'CHI LEG 4 PCS', price: 200 },
    { name: 'Chi Legs 4pcs', price: 200 },
    { name: 'CHI LOLLYPOP 4PCS', price: 160 },
    { name: 'CHI NUGGATS', price: 130 },
    { name: 'Chi Nuggets 6pcs', price: 130 },
    { name: 'Chi Popcorn', price: 150 },
    { name: 'Chi Sandwich', price: 120 },
    { name: 'CHI WINGS', price: 140 },
    { name: 'Chi Wings 6pcs', price: 140 },
    { name: 'CHI WRAPS', price: 140 },
    { name: 'CHICKEN BURGER', price: 120 },
    { name: 'Chicken Chees Sandwich', price: 150 },
    { name: 'Chicken Cheese Balls 5pcs', price: 160 },
    { name: 'Chicken Cheese Garlic 5pcs', price: 170 },
    { name: 'CHICKEN CHEESE PIZZA', price: 220 },
    { name: 'Chicken Legs 2 Pcs', price: 110 },
    { name: 'Chicken Momos 8pcs', price: 120 },
    { name: 'CHICKEN POPCORN', price: 150 },
    { name: 'Chicken Roll 4pcs', price: 140 },
    { name: 'Chicken Samosa 5 Pcs', price: 100 },
    { name: 'Chicken Sandwich', price: 120 },
    { name: 'CORN CHICKEN PIZZA', price: 210 },
    { name: 'CRISPY CHICKEN BURGER', price: 130 },
    { name: 'CRISPY CHICKEN PIZZA', price: 230 },
    { name: 'FRENCH FRYS', price: 80 },
    { name: 'GARDEN FRESH PIZZA', price: 180 },
    { name: 'MASALA FRENCH FRYS', price: 90 },
    { name: 'MUSHROOM CHICKEN PIZZA', price: 220 },
    { name: 'Paneer Momos 8pcs', price: 110 },
    { name: 'Paneer Popcorn', price: 140 },
    { name: 'Paneer Sticks 5pcs', price: 130 },
    { name: 'PANNER BURGER', price: 110 },
    { name: 'PANNER PIZZA', price: 190 },
    { name: 'Panner Rolls 4 Pcs', price: 130 },
    { name: 'Potato Cheese Balls 6pcs', price: 120 },
    { name: 'SPL VEG PIZZA', price: 200 },
    { name: 'Sweet Corn Samll Roll 5pcs', price: 100 },
    { name: 'VEG BURGER', price: 90 },
    { name: 'Veg Chees Burger', price: 110 },
    { name: 'VEG CHEES PIZZA', price: 170 },
    { name: 'Veg Chees Sandwich', price: 120 },
    { name: 'VEG CHEESE BURGER', price: 110 },
    { name: 'VEG CORN PIZZA', price: 160 },
    { name: 'Veg Corn Sandwich', price: 110 },
    { name: 'VEG HEESE SANDWICH', price: 120 },
    { name: 'Veg Lollipop 5pcs', price: 110 },
    { name: 'Veg Momos 8 Pcs', price: 100 },
    { name: 'VEG MUSHROOM PIZZA', price: 180 },
    { name: 'Veg Mushroom Sandwich', price: 120 },
    { name: 'VEG NUGGETS', price: 100 },
    { name: 'Veg Nuggets 6pcs', price: 100 },
    { name: 'Veg Panner Sandwich', price: 120 },
    { name: 'Veg Rolls 4pcs', price: 110 },
    { name: 'VEG ROLLS 6 PCS', price: 150 },
    { name: 'VEG SANDWICH', price: 90 }
  ],
  'Beverages & Cool Drinks': [
    { name: 'COOL DRINK', price: 40 },
    { name: 'Limca', price: 40 },
    { name: 'Maaza', price: 40 },
    { name: 'Pulpy Orange', price: 45 },
    { name: 'Shoda Small', price: 20 },
    { name: 'SODA', price: 20 },
    { name: 'Soda 10rs', price: 10 },
    { name: 'Spite', price: 40 },
    { name: 'TENDER COCONUT', price: 60 },
    { name: 'Tender Coconut 1000ml', price: 120 },
    { name: 'Tender Coconut 500 Ml', price: 60 },
    { name: 'Tender Coconut Bulk', price: 200 },
    { name: 'TENDER COCONUT(SPECIAL )', price: 80 },
    { name: 'Thumsup', price: 40 },
    { name: 'WATER BOTTLE', price: 20 },
    { name: 'Water Bottle 1/2 Ltr', price: 10 },
    { name: 'WATER BOTTLE 1L', price: 20 },
    { name: 'Watermilon', price: 40 }
  ],
  'Miscellaneous': [
    { name: '3 MAN IN A BOAT', price: 150 },
    { name: 'BERRY BEERY', price: 120 },
    { name: 'OPEN ITEM', price: 100 },
    { name: 'Orange', price: 80 },
    { name: 'Promogrant', price: 90 },
    { name: 'TEST KOT', price: 10 }
  ]
};

const categoryIcons = {
  'Ice Creams & Desserts': '🍦',
  'Milkshakes & Mocktails': '🥤',
  'Fresh Juices': '🧃',
  'Fast Food & Snacks': '🍔',
  'Beverages & Cool Drinks': '🍹',
  'Miscellaneous': '🍽️'
};

const OUTLET_ID = 'out_main';

async function seed() {
  try {
    for (const [catName, items] of Object.entries(itemsByCategory)) {
      console.log(`Processing category: ${catName}`);
      
      // Check if category exists
      const { rows: existingCats } = await db.query(
        'SELECT * FROM categories WHERE name = $1 AND outlet_id = $2', 
        [catName, OUTLET_ID]
      );
      
      let catId;
      if (existingCats.length > 0) {
        catId = existingCats[0].id;
      } else {
        catId = `c${Date.now()}_${Math.floor(Math.random() * 1000)}`;
        await db.query(
          'INSERT INTO categories (id, name, icon, sort_order, outlet_id) VALUES ($1, $2, $3, $4, $5)',
          [catId, catName, categoryIcons[catName], 0, OUTLET_ID]
        );
      }
      
      for (const item of items) {
        const itemId = `m${Date.now()}_${Math.floor(Math.random() * 10000)}`;
        
        // Extract type
        let type = 'veg';
        const nameLower = item.name.toLowerCase();
        if (nameLower.includes('chicken') || nameLower.includes('chi ')) {
          type = 'non-veg';
        }
        
        // Insert item
        await db.query(
          `INSERT INTO menu_items (id, name, price, cost, type, active, available_dine, available_takeaway, available_delivery, category_id, outlet_id) 
           VALUES ($1, $2, $3, $4, $5, true, true, true, true, $6, $7)`,
          [itemId, item.name, item.price, item.price * 0.4, type, catId, OUTLET_ID]
        );
      }
    }
    console.log('✅ Seeding complete!');
    process.exit(0);
  } catch (e) {
    console.error('Error:', e);
    process.exit(1);
  }
}

seed();
